services:
  prometheus:
    image: prometheus-mz
    depends_on:
      - metricexampleapi
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    networks:
      - backend
      
  metricexampleapi:
    image: metricexample.api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8380:80
    networks:
      - backend

  grafana:
    image: grafana-mz
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - backend

volumes:
  prometheus_data: {}
  grafana_data: {}
  metricexample_data: {}

networks:
  backend: